/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateNoteIndexRouteImport } from './routes/create-note/index'
import { Route as EditNoteIdIndexRouteImport } from './routes/edit-note/$id/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateNoteIndexRoute = CreateNoteIndexRouteImport.update({
  id: '/create-note/',
  path: '/create-note/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditNoteIdIndexRoute = EditNoteIdIndexRouteImport.update({
  id: '/edit-note/$id/',
  path: '/edit-note/$id/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-note': typeof CreateNoteIndexRoute
  '/edit-note/$id': typeof EditNoteIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-note': typeof CreateNoteIndexRoute
  '/edit-note/$id': typeof EditNoteIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-note/': typeof CreateNoteIndexRoute
  '/edit-note/$id/': typeof EditNoteIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-note' | '/edit-note/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-note' | '/edit-note/$id'
  id: '__root__' | '/' | '/create-note/' | '/edit-note/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateNoteIndexRoute: typeof CreateNoteIndexRoute
  EditNoteIdIndexRoute: typeof EditNoteIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-note/': {
      id: '/create-note/'
      path: '/create-note'
      fullPath: '/create-note'
      preLoaderRoute: typeof CreateNoteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-note/$id/': {
      id: '/edit-note/$id/'
      path: '/edit-note/$id'
      fullPath: '/edit-note/$id'
      preLoaderRoute: typeof EditNoteIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateNoteIndexRoute: CreateNoteIndexRoute,
  EditNoteIdIndexRoute: EditNoteIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
